name: PizzaKartRacers
version: '${project.version}'
main: me.pizzathatcodes.pizzakartracers.Main
api-version: '1.20'
author: PizzaThatCodes
description: A plugin that adds PizzaKartRacers to Minecraft.
depend:
  - ProtocolLib
commands:
  setTimer:
    description: Set the timer for the game.
    usage: /setTimer <time>
    permission: pizzakartracers.settimer
